/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OnboardImport } from './routes/onboard'
import { Route as DemoRequestImport } from './routes/demo-request'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as BiddingIdImport } from './routes/bidding/$id'
import { Route as AuctionsIdImport } from './routes/auctions/$id'

// Create/Update Routes

const OnboardRoute = OnboardImport.update({
  path: '/onboard',
  getParentRoute: () => rootRoute,
} as any)

const DemoRequestRoute = DemoRequestImport.update({
  path: '/demo-request',
  getParentRoute: () => rootRoute,
} as any)

const DashboardRoute = DashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BiddingIdRoute = BiddingIdImport.update({
  path: '/bidding/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuctionsIdRoute = AuctionsIdImport.update({
  path: '/auctions/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/demo-request': {
      id: '/demo-request'
      path: '/demo-request'
      fullPath: '/demo-request'
      preLoaderRoute: typeof DemoRequestImport
      parentRoute: typeof rootRoute
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardImport
      parentRoute: typeof rootRoute
    }
    '/auctions/$id': {
      id: '/auctions/$id'
      path: '/auctions/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuctionsIdImport
      parentRoute: typeof rootRoute
    }
    '/bidding/$id': {
      id: '/bidding/$id'
      path: '/bidding/$id'
      fullPath: '/bidding/$id'
      preLoaderRoute: typeof BiddingIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DashboardRoute,
  DemoRequestRoute,
  OnboardRoute,
  AuctionsIdRoute,
  BiddingIdRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard",
        "/demo-request",
        "/onboard",
        "/auctions/$id",
        "/bidding/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx"
    },
    "/demo-request": {
      "filePath": "demo-request.tsx"
    },
    "/onboard": {
      "filePath": "onboard.tsx"
    },
    "/auctions/$id": {
      "filePath": "auctions/$id.tsx"
    },
    "/bidding/$id": {
      "filePath": "bidding/$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
